default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: 5
  username: rafaelnaves
  password: 
  host: localhost

development:
  <<: *default
  database: sales_admin_development

test:
  <<: *default
  database: sales_admin_test